# Lançamento de Moedas:
# Faça um programa para lançar uma moeda. Quando chamamos uma função, ela deve 
# retornar “cara” ou “coroa”. Em outra função, faça ‘n’ lançamentos de moedas (onde ‘n’ é o 
# valor que o usuário quiser) e mostre a porcentagem de vezes que deu cara e coroa. O que 
# tende a acontecer se você jogar a moeda 10, 100, 1000 ou um milhão de vezes?

import random
def moeda ():
    if 



moeda()


def lancamento():
    n = int(input("Digite quantas vezes vc quer lançar a moeda: "))
    resultado = random.choice(['cara','coroa'])
    return resultado



lancamento()