# 42. Faça um programa que receba o valor de uma dívida e mostre uma 
# tabela com os seguintes dados: valor da dívida, valor dos juros, quantidade 
# de parcelas e valor da parcela. 
# a. Os juros e a quantidade de parcelas seguem a tabela abaixo: 
# b. Quantidade de Parcelas % de Juros sobre o valor 
# inicial da dívida 
# c. 1 0 
# d. 3 10 
# e. 6 15 
# f. 9 20 
# 12 25 
# Exemplo de saída do programa: 
# Valor da Dívida Valor dos Juros Quantidade de Parcelas Valor da 
# Parcela 
# R$ 1.000,00 0 1 R$ 
# 1.000,00 
# R$ 1.100,00 100 3 R$ 
# 366,00 
# R$ 1.150,00 150 6 R$ 
# 191,67 
