# 43. Faça um programa que leia uma quantidade indeterminada de 
# números positivos e conte quantos deles estão nos seguintes intervalos: [0-
# 25], [26-50], [51-75] e [76-100]. A entrada de dados deverá terminar quando 
# for lido um número negativo. 
# 44. O cardápio de uma lanchonete é o seguinte: 
# a. Especificação Código Preço 
# b. Cachorro Quente 100 R$ 1,20 
# c. Bauru Simples 101 R$ 1,30 
# d. Bauru com ovo 102 R$ 1,50 
# e. Hambúrguer 103 R$ 1,20 
# f. Cheeseburguer 104 R$ 1,30 
# g. Refrigerante 105 R$ 1,00 

# Faça um programa que leia o código dos itens pedidos e as quantidades 
# desejadas. Calcule e mostre o valor a ser pago por item (preço * 
# quantidade) e o total geral do pedido. Considere que o cliente deve informar 
# quando o pedido deve ser encerrado. 