# 45. Em uma eleição presidencial existem quatro candidatos. Os votos 
# são informados por meio de código. Os códigos utilizados são: 
# a. 1 , 2, 3, 4 - Votos para os respectivos candidatos 
# b. (você deve montar a tabela ex: 1 - Jose/ 2- João/etc) 
# c. 5 - Voto Nulo 
# d. 6 - Voto em Branco 
# Faça um programa que calcule e mostre: 
# e. O total de votos para cada candidato; 
# f. O total de votos nulos; 
# g. O total de votos em branco; 
# h. A percentagem de votos nulos sobre o total de votos; 
# i. A percentagem de votos em branco sobre o total de votos. Para 
# finalizar o conjunto de votos tem-se o valor zero. 
