# 47. Em uma competição de salto em distância cada atleta tem direito a 
# cinco saltos. No final da série de saltos de cada atleta, o melhor e o pior 
# resultados são eliminados. O seu resultado fica sendo a média dos três 
# valores restantes. Você deve fazer um programa que receba o nome e as 
# cinco distâncias alcançadas pelo atleta em seus saltos e depois informe a 
# média dos saltos conforme a descrição acima informada (retirar o melhor e 
# o pior salto e depois calcular a média). Faça uso de uma lista para 
# armazenar os saltos. Os saltos são informados na ordem da execução, 
# portanto não são ordenados. O programa deve ser encerrado quando não 
# for informado o nome do atleta. A saída do programa deve ser conforme o 
# exemplo abaixo: 
# 48. Atleta: Rodrigo Curvêllo 
# 49.
# 50. Primeiro Salto: 6.5 m 
# 51. Segundo Salto: 6.1 m 
# 52. Terceiro Salto: 6.2 m 
# 53. Quarto Salto: 5.4 m 
# 54. Quinto Salto: 5.3 m 
# 55.
# 56. Melhor salto: 6.5 m 
# 57. Pior salto: 5.3 m 
# 58. Média dos demais saltos: 5.9 m 
# 59.
# 60. Resultado final: 
# Rodrigo Curvêllo: 5.9 m 
