# 61. Em uma competição de ginástica, cada atleta recebe votos de sete 
# jurados. A melhor e a pior nota são eliminadas. A sua nota fica sendo a 
# média dos votos restantes. Você deve fazer um programa que receba o 
# nome do ginasta e as notas dos sete jurados alcançadas pelo atleta em sua 
# apresentação e depois informe a sua média, conforme a descrição acima 
# informada (retirar o melhor e o pior salto e depois calcular a média com as 
# notas restantes). As notas não são informados ordenadas. Um exemplo de 
# saída do programa deve ser conforme o exemplo abaixo: 
# 62. Atleta: Aparecido Parente 
# 63. Nota: 9.9 
# 64. Nota: 7.5 
# 65. Nota: 9.5 
# 66. Nota: 8.5 
# 67. Nota: 9.0 
# 68. Nota: 8.5 
# 69. Nota: 9.7 
# 70.
# 71. Resultado final: 
# 72. Atleta: Aparecido Parente 
# 73. Melhor nota: 9.9 
# 74. Pior nota: 7.5 
# Média: 9,04 
